# Generated by Django 5.2.7 on 2025-11-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.author')),
            ],
            options={
                'db_table': 'author_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.genre')),
            ],
            options={
                'db_table': 'genre_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.position')),
                ('store', models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(db_column='purchase_id', primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client')),
                ('employee', models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee')),
                ('store', models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('isbn', models.TextField(blank=True, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('publisher', models.ForeignKey(db_column='publisher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.publisher')),
                ('author', models.ManyToManyField(related_name='books', through='store.AuthorBook', to='store.author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(related_name='genres', through='store.GenreBook', to='store.book'),
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchase', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.purchase')),
                ('quantity', models.IntegerField()),
                ('price_at_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
            options={
                'db_table': 'purchase_detail',
                'unique_together': {('purchase', 'book')},
            },
        ),
    ]
