# Generated by Django 5.2.7 on 2025-11-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrebook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genrebook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='genrebook',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='store.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(to='store.book'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='position',
            name='position_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(db_column='purchase_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.publisher'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.purchase'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='position',
            table='position',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
        migrations.AlterModelTable(
            name='purchasedetail',
            table='purchase_detail',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
        migrations.DeleteModel(
            name='GenreBook',
        ),
    ]
