# Generated by Django 5.2.7 on 2025-12-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='store.publisher'),
        ),
    ]
