# Generated by Django 5.2.7 on 2025-11-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_genrebook_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.author')),
            ],
            options={
                'db_table': 'author_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.genre')),
            ],
            options={
                'db_table': 'genre_book',
                'managed': False,
            },
        ),
    ]
