# Generated by Django 5.2.7 on 2025-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_authorbook_genrebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', through='store.AuthorBook', to='store.author'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(related_name='genres', through='store.GenreBook', to='store.book'),
        ),
    ]
